server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka


# all service different port pe run ho raha tha but ab sab service 8080 pe run honge because of gateway service
spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service # UserService
              uri: lb://USER-SERVICE
              predicates:
                - Path=/api/users/**
            - id: activity-service # ActivityService
              uri: lb://ACTIVITY-SERVICE
              predicates:
                - Path=/api/activities/**
            - id: ai-service # AiService
              uri: lb://AI-SERVICE
              predicates:
                - Path=/api/recommendations/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8181/realms/Fitness-App/protocol/openid-connect/certs
